"""Walk a vault and report its structure.

This is a *reader*. It opens files, never writes them, and holds no path to a vault
beyond the one it is handed.

Two deliberate non-features, because both would be defects rather than omissions:

**It does not parse YAML.** Frontmatter is read for its keys and for the *shape* of each
value — a bare scalar, a comma-joined string, a block list — and the raw text is kept
verbatim. A real vault spells the same field both ways (`location: Riverfold` in one
note, `location: Riverfold, The Long Marsh` in another), and a YAML round-trip would
quietly normalise one into the other on any note a tool touched. The survey exists to
report that drift, so it must not be built on something that erases it.

**It does not resolve a link the way a filesystem would.** Obsidian resolves a bare
`[[Target]]` against every note in the vault by basename, so note titles are one global
namespace regardless of folder. The resolution here reproduces that, including its
failure mode: two notes with the same stem make every bare link to that stem ambiguous.
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path

FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|\Z)", re.DOTALL)
"""Frontmatter is only frontmatter at the very start of the file. A `---` further down
is a horizontal rule, and treating it as a delimiter would swallow the note's prose."""

_FM_KEY = re.compile(r"^([A-Za-z0-9_][A-Za-z0-9_\- ]*):[ \t]*(.*)$")
_FM_ITEM = re.compile(r"^[ \t]*-[ \t]+\S")
_HEADING = re.compile(r"^(#{1,6})[ \t]+(.+?)[ \t]*$", re.MULTILINE)
_WIKILINK = re.compile(r"(!?)\[\[([^\]\n]+)\]\]")
_SESSION_REF = re.compile(r"\bsession[ \t]*#?(\d+)\b", re.IGNORECASE)

SCALAR = "scalar"
COMMA_STRING = "comma-string"
BLOCK_LIST = "block-list"
EMPTY = "empty"

ASSET_SUFFIXES = frozenset({".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".pdf"})

LINK_SUFFIXES = ASSET_SUFFIXES | {".md"}
"""Extensions a link target may carry that are not part of the note's title."""

PROVENANCE_KEYS = frozenset(
    {
        "generated",
        "generated_by",
        "generated_at",
        "generated_on",
        "provenance",
        "authored_by",
        "author",
        "created_by",
        "source_tool",
        "tool",
    }
)
"""Frontmatter keys that would distinguish authored content from generated content.

Compared after normalising separators, because the key syntax a vault may use is wider
than one spelling: `generated-by`, `generated by` and `generated_by` are one key as far
as the person writing it is concerned. Matching only the underscored form would have made
the "no vault carries a provenance signal" finding weaker than it reads -- a vault could
have carried one and been reported as carrying none.
"""


def _normalise_key(key: str) -> str:
    return re.sub(r"[\s\-]+", "_", key.strip().lower())


def ranked(counts: Counter[str]) -> list[tuple[str, int]]:
    """Counter entries, most frequent first, ties broken by name.

    `Counter.most_common()` leaves ties in insertion order, and insertion order here comes
    from iterating sets, which Python does not keep stable between processes. The survey
    report is evidence -- `docs/VAULT_INTEGRATION.md` asks a reader to hold it against a
    written list -- and evidence that reorders itself between two honest runs is evidence
    somebody has to squint at before believing.
    """
    return sorted(counts.items(), key=lambda item: (-item[1], item[0]))


DEFAULT_IGNORED_DIRECTORIES = frozenset({".obsidian", ".trash", ".git", ".claude"})
"""Application state, not vault content. `.obsidian` in particular rewrites itself as
soon as a pane moves, so counting it would make every survey of a vault somebody has
open disagree with the last one."""

DEFAULT_IGNORED_FILENAMES = frozenset({".DS_Store", "Thumbs.db", "desktop.ini"})
"""The same problem at file granularity, from the operating system rather than the app.

A `.DS_Store` is rewritten when somebody opens the folder in a file browser. Counting
one would report a vault as modified because a person looked at it, which is a false
positive in the one check whose value depends on being believed."""


@dataclass(frozen=True)
class FrontmatterField:
    """One frontmatter key, its raw value text, and which of three shapes it took."""

    key: str
    shape: str
    raw: str


@dataclass(frozen=True)
class Link:
    """One `[[wikilink]]`, decomposed but not resolved."""

    target: str
    anchor: str | None = None
    display: str | None = None
    is_embed: bool = False

    @property
    def basename(self) -> str:
        """What Obsidian matches on: the last path segment, minus a *file* extension.

        Only a known extension is stripped. Treating every dot as a suffix boundary was
        wrong: a note may legitimately have a dot in its title, and `[[Dr. Grey]]` would
        have resolved as `Dr` -- mis-resolving a valid link and reporting a note that
        exists as one that does not.
        """
        tail = self.target.rsplit("/", 1)[-1]
        suffix = Path(tail).suffix.lower()
        return tail[: -len(suffix)] if suffix in LINK_SUFFIXES else tail

    @property
    def is_path_qualified(self) -> bool:
        return "/" in self.target


@dataclass(frozen=True)
class Section:
    """A heading and where it sits.

    `session_ref` is the session number named in the heading, when the heading names
    one. It is how an accumulating note is recognised: an entity note that gains
    `## Rescued from the mine (Session 4)` is recording that a session changed it.
    """

    level: int
    title: str
    line: int
    index: int
    session_ref: int | None = None


@dataclass(frozen=True)
class Note:
    path: str
    folder: str
    title: str
    note_type: str | None
    frontmatter: tuple[FrontmatterField, ...]
    sections: tuple[Section, ...]
    links: tuple[Link, ...]
    h1: str | None
    size_bytes: int

    @property
    def is_stub(self) -> bool:
        """No content of its own.

        Not the same as absent, and the difference is the whole point. A stub is a note
        somebody created deliberately so that links to it would resolve; it records an
        intention to write something. Filling one in is a different act from creating a
        note that was not there.
        """
        return not self.sections and not self.frontmatter and self.size_bytes < 16

    @property
    def title_matches_h1(self) -> bool:
        return self.h1 is not None and self.h1 == self.title

    def frontmatter_keys(self) -> tuple[str, ...]:
        return tuple(field.key for field in self.frontmatter)

    def body_sections(self) -> tuple[Section, ...]:
        """Sections below the title, which is the level a convention lives at."""
        return tuple(section for section in self.sections if section.level >= 2)


@dataclass(frozen=True)
class LinkTopology:
    total: int
    distinct_targets: int
    resolved: int
    unresolved: int
    ambiguous: int
    piped: int
    anchored: int
    path_qualified: int
    embeds_to_asset: int
    embeds_to_note: int

    @property
    def unresolved_share(self) -> float:
        return self.unresolved / self.total if self.total else 0.0


@dataclass(frozen=True)
class VaultSurvey:
    """Everything the walk found, and the derived views a reader can check it by."""

    root: Path
    notes: tuple[Note, ...]
    asset_names: frozenset[str]

    def note_types(self) -> Counter[str]:
        """Declared `type:` values. A note without one is counted as `(untyped)`."""
        return Counter(note.note_type or "(untyped)" for note in self.notes)

    def folders(self) -> Counter[str]:
        return Counter(note.folder for note in self.notes)

    def frontmatter_keys(self) -> Counter[str]:
        counts: Counter[str] = Counter()
        for note in self.notes:
            counts.update(note.frontmatter_keys())
        return counts

    def frontmatter_keys_by_type(self) -> dict[str, Counter[str]]:
        grouped: dict[str, Counter[str]] = defaultdict(Counter)
        for note in self.notes:
            grouped[note.note_type or "(untyped)"].update(note.frontmatter_keys())
        return dict(grouped)

    def inconsistent_value_shapes(self) -> dict[str, tuple[str, ...]]:
        """Keys whose *values* take more than one shape across the vault.

        This is about value shape, not key spelling -- the two are different findings and
        conflating them in the wording made this read as something it does not do. A key
        here is one a consumer cannot infer arity for: `affiliation` holding a bare name
        in one note and two comma-joined names in another means a tool reading it has to
        accept both and must not rewrite either into the other. Key *spelling* drift
        (`related_npcs` against `related npcs`) is a separate question this does not
        answer; `_normalise_key` is where that idea lives.
        """
        shapes: dict[str, set[str]] = defaultdict(set)
        for note in self.notes:
            for field in note.frontmatter:
                shapes[field.key].add(field.shape)
        return {key: tuple(sorted(found)) for key, found in shapes.items() if len(found) > 1}

    def _stems(self) -> dict[str, list[Note]]:
        by_stem: dict[str, list[Note]] = defaultdict(list)
        for note in self.notes:
            by_stem[note.title].append(note)
        return by_stem

    def link_topology(self) -> LinkTopology:
        by_stem = self._stems()
        targets: Counter[str] = Counter()
        resolved = unresolved = ambiguous = piped = anchored = qualified = 0
        embeds_asset = embeds_note = 0
        for note in self.notes:
            for link in note.links:
                if link.is_embed:
                    # An embed is an asset when it names one, not when it merely
                    # contains a dot. `![[Dr. Grey]]` transcludes a note, and
                    # `![[Note.md]]` transcludes a note whose link spells the extension
                    # out -- treating either as an image is the same dot-in-title
                    # mistake `Link.basename` had.
                    name = link.target.rsplit("/", 1)[-1]
                    if name in self.asset_names or Path(name).suffix.lower() in ASSET_SUFFIXES:
                        embeds_asset += 1
                    else:
                        embeds_note += 1
                    continue
                targets[link.basename] += 1
                if link.display is not None:
                    piped += 1
                if link.anchor is not None:
                    anchored += 1
                if link.is_path_qualified:
                    qualified += 1
                hits = by_stem.get(link.basename, [])
                if not hits:
                    unresolved += 1
                elif len(hits) > 1:
                    ambiguous += 1
                else:
                    resolved += 1
        return LinkTopology(
            total=resolved + unresolved + ambiguous,
            distinct_targets=len(targets),
            resolved=resolved,
            unresolved=unresolved,
            ambiguous=ambiguous,
            piped=piped,
            anchored=anchored,
            path_qualified=qualified,
            embeds_to_asset=embeds_asset,
            embeds_to_note=embeds_note,
        )

    def unresolved_targets(self) -> Counter[str]:
        """Link targets no note answers to.

        Ordinary, not broken: a vault names things before it writes them up. A contract
        that treated these as errors to repair would generate notes nobody asked for.
        """
        by_stem = self._stems()
        missing: Counter[str] = Counter()
        for note in self.notes:
            for link in note.links:
                if not link.is_embed and link.basename not in by_stem:
                    missing[link.basename] += 1
        return missing

    def ambiguous_titles(self) -> tuple[str, ...]:
        """Titles held by more than one note, which every bare link to them cannot tell apart."""
        return tuple(sorted(stem for stem, notes in self._stems().items() if len(notes) > 1))

    def stubs(self) -> tuple[Note, ...]:
        return tuple(note for note in self.notes if note.is_stub)

    def accumulating_notes(self) -> tuple[Note, ...]:
        """Notes carrying at least one session-stamped section."""
        return tuple(
            note
            for note in self.notes
            if any(section.session_ref is not None for section in note.body_sections())
        )

    def accumulation_positions(self) -> Counter[str]:
        """Where session-stamped sections sit inside their note.

        The answer decides whether a change can be appended. A section that lands in the
        middle two thirds was placed where it belonged in the note's own order, not at
        the end of the file.
        """
        positions: Counter[str] = Counter()
        for note in self.notes:
            sections = note.body_sections()
            if not sections:
                continue
            last = len(sections) - 1
            for section in sections:
                if section.session_ref is None:
                    continue
                fraction = section.index / last if last else 0.0
                if fraction < 1 / 3:
                    positions["first-third"] += 1
                elif fraction < 2 / 3:
                    positions["middle-third"] += 1
                else:
                    positions["last-third"] += 1
                if section.index == last:
                    positions["final-section-in-note"] += 1
        return positions

    def opening_sections(self) -> Counter[str]:
        return Counter(
            note.body_sections()[0].title for note in self.notes if note.body_sections()
        )

    def terminal_sections(self) -> Counter[str]:
        return Counter(
            note.body_sections()[-1].title for note in self.notes if note.body_sections()
        )

    def recurring_sections_by_type(self, minimum: int = 2) -> dict[str, tuple[tuple[str, int], ...]]:
        """Section titles shared by at least `minimum` notes of the same declared type.

        Shared titles are the convention; a title used once is that note's own content.
        """
        grouped: dict[str, Counter[str]] = defaultdict(Counter)
        for note in self.notes:
            grouped[note.note_type or "(untyped)"].update(
                {section.title for section in note.body_sections()}
            )
        return {
            note_type: tuple(
                (title, count) for title, count in ranked(counts) if count >= minimum
            )
            for note_type, counts in sorted(grouped.items())
        }

    def provenance_signals(self) -> tuple[str, ...]:
        """Frontmatter keys that could distinguish authored from generated content.

        Returned so that a caller can see the answer rather than be told it. An empty
        result means the vault carries no such signal, which is the finding that forces
        the boundary in `boundary.py` to be established by the tool instead of read off
        the vault.
        """
        found = {
            field.key
            for note in self.notes
            for field in note.frontmatter
            if _normalise_key(field.key) in PROVENANCE_KEYS
        }
        return tuple(sorted(found))


def _parse_frontmatter(text: str) -> tuple[tuple[FrontmatterField, ...], str]:
    match = FRONTMATTER.match(text)
    if not match:
        return (), text
    fields: list[FrontmatterField] = []
    lines = match.group(1).splitlines()
    for position, line in enumerate(lines):
        key_match = _FM_KEY.match(line)
        if not key_match:
            continue
        key, raw = key_match.group(1).strip(), key_match.group(2).strip()
        following = lines[position + 1] if position + 1 < len(lines) else ""
        if _FM_ITEM.match(following):
            shape = BLOCK_LIST
        elif not raw:
            shape = EMPTY
        elif "," in raw:
            shape = COMMA_STRING
        else:
            shape = SCALAR
        fields.append(FrontmatterField(key=key, shape=shape, raw=raw))
    return tuple(fields), text[match.end() :]


def _parse_sections(body: str, offset_lines: int) -> tuple[Section, ...]:
    sections: list[Section] = []
    body_index = 0
    for match in _HEADING.finditer(body):
        title = match.group(2).strip()
        line = offset_lines + body.count("\n", 0, match.start()) + 1
        session = _SESSION_REF.search(title)
        level = len(match.group(1))
        index = body_index if level >= 2 else -1
        if level >= 2:
            body_index += 1
        sections.append(
            Section(
                level=level,
                title=title,
                line=line,
                index=index,
                session_ref=int(session.group(1)) if session else None,
            )
        )
    return tuple(sections)


def _parse_links(text: str) -> tuple[Link, ...]:
    links: list[Link] = []
    for bang, inner in _WIKILINK.findall(text):
        target, _, display = inner.partition("|")
        anchor: str | None = None
        if "#" in target:
            target, _, anchor = target.partition("#")
        links.append(
            Link(
                target=target.strip(),
                anchor=anchor.strip() if anchor else None,
                display=display.strip() if display else None,
                is_embed=bool(bang),
            )
        )
    return tuple(links)


def read_note(path: Path, root: Path) -> Note:
    text = path.read_text(encoding="utf-8", errors="replace")
    fields, body = _parse_frontmatter(text)
    offset_lines = text[: len(text) - len(body)].count("\n")
    sections = _parse_sections(body, offset_lines)
    relative = path.relative_to(root)
    h1 = next((section.title for section in sections if section.level == 1), None)
    declared = next((field.raw for field in fields if field.key == "type"), None)
    return Note(
        path=relative.as_posix(),
        folder=relative.parent.as_posix(),
        title=path.stem,
        note_type=declared or None,
        frontmatter=fields,
        sections=sections,
        links=_parse_links(text),
        h1=h1,
        size_bytes=len(text.encode("utf-8")),
    )


def survey_vault(
    root: Path,
    *,
    ignored_directories: frozenset[str] = DEFAULT_IGNORED_DIRECTORIES,
) -> VaultSurvey:
    """Read every markdown note under `root` and report what is there.

    Raises `NotADirectoryError` rather than returning an empty survey for a path that is
    not a vault: an empty result and a wrong path look identical to a caller, and one of
    them is a mistake worth stopping on.
    """
    root = Path(root)
    if not root.is_dir():
        raise NotADirectoryError(f"not a vault directory: {root}")

    def included(path: Path) -> bool:
        return not any(part in ignored_directories for part in path.relative_to(root).parts)

    notes = tuple(
        read_note(path, root)
        for path in sorted(root.rglob("*.md"))
        if path.is_file() and included(path)
    )
    assets = frozenset(
        path.name
        for path in root.rglob("*")
        if path.is_file() and path.suffix.lower() in ASSET_SUFFIXES and included(path)
    )
    return VaultSurvey(root=root, notes=notes, asset_names=assets)


def format_report(survey: VaultSurvey) -> str:
    """The survey as a list a second party can walk against a written characterisation.

    Every line is a claim the walk can be re-run to check. It is printed rather than
    summarised because a summary is the author's reading, and the point of this report
    is to let somebody else do the reading.
    """
    topology = survey.link_topology()
    accumulating = survey.accumulating_notes()
    lines: list[str] = []

    def section(name: str) -> None:
        lines.append("")
        lines.append(name)
        lines.append("-" * len(name))

    lines.append(f"vault: {survey.root}")
    lines.append(f"notes: {len(survey.notes)}")
    lines.append(f"notes with frontmatter: {sum(1 for n in survey.notes if n.frontmatter)}")
    lines.append(f"stub notes (created as link targets, no content): {len(survey.stubs())}")
    lines.append(
        f"title matches its own H1: {sum(1 for n in survey.notes if n.title_matches_h1)}"
        f" of {sum(1 for n in survey.notes if n.h1)} notes carrying an H1"
    )

    section("note types (declared `type:`)")
    for note_type, count in ranked(survey.note_types()):
        lines.append(f"  {count:5d}  {note_type}")

    section("folders")
    for folder, count in sorted(survey.folders().items()):
        lines.append(f"  {count:5d}  {folder or '.'}")

    section("frontmatter keys by note type")
    for note_type, keys in sorted(survey.frontmatter_keys_by_type().items()):
        rendered = ", ".join(f"{key}({count})" for key, count in ranked(keys))
        lines.append(f"  {note_type}: {rendered}")

    section("frontmatter keys whose values take more than one shape")
    drift = survey.inconsistent_value_shapes()
    if drift:
        for key, shapes in sorted(drift.items()):
            lines.append(f"  {key}: {' + '.join(shapes)}")
    else:
        lines.append("  (none)")

    section("link topology")
    lines.append(f"  total links: {topology.total}")
    lines.append(f"  distinct targets: {topology.distinct_targets}")
    lines.append(f"  resolved: {topology.resolved}")
    lines.append(f"  unresolved: {topology.unresolved} ({topology.unresolved_share:.1%})")
    lines.append(f"  ambiguous (title held by two notes): {topology.ambiguous}")
    lines.append(f"  piped [[target|display]]: {topology.piped}")
    lines.append(f"  heading-anchored [[target#section]]: {topology.anchored}")
    lines.append(f"  folder-qualified [[folder/target]]: {topology.path_qualified}")
    lines.append(f"  embeds to an asset: {topology.embeds_to_asset}")
    lines.append(f"  embeds to a note: {topology.embeds_to_note}")
    lines.append(f"  titles held by more than one note: {len(survey.ambiguous_titles())}")

    section("accumulation (sections naming a session)")
    lines.append(f"  notes carrying at least one: {len(accumulating)}")
    for bucket, count in sorted(survey.accumulation_positions().items()):
        lines.append(f"  {bucket}: {count}")

    section("section conventions")
    opening = ranked(survey.opening_sections())[:1]
    terminal = ranked(survey.terminal_sections())[:1]
    if opening:
        lines.append(f"  most common opening section: {opening[0][0]} ({opening[0][1]} notes)")
    if terminal:
        lines.append(f"  most common closing section: {terminal[0][0]} ({terminal[0][1]} notes)")
    for note_type, recurring in survey.recurring_sections_by_type().items():
        if recurring:
            rendered = ", ".join(f"{title}({count})" for title, count in recurring)
            lines.append(f"  {note_type}: {rendered}")

    section("provenance")
    signals = survey.provenance_signals()
    lines.append(
        f"  frontmatter keys distinguishing authored from generated: {', '.join(signals)}"
        if signals
        else "  frontmatter keys distinguishing authored from generated: (none)"
    )
    return "\n".join(lines) + "\n"
